// This file is automatically generated. Do not edit it directly.
import { Pool } from 'pg';
import dotenv from 'dotenv';

dotenv.config(); // Load environment variables from .env

// Database configuration for Supabase PostgreSQL
const pgConfig = {
  user: process.env.DB_USER,        // Supabase database username
  host: process.env.DB_HOST,        // Supabase host
  database: process.env.DB_NAME,    // Supabase database name
  password: process.env.DB_PASSWORD, // Supabase password
  port: Number(process.env.DB_PORT) || 5432, // Supabase port (default 5432)
  ssl: {
    rejectUnauthorized: false,  // Required for Supabase connections
  },
};

// Create a connection pool
export const dbPool = new Pool(pgConfig);

// Test the connection
dbPool.connect((err) => {
  if (err) {
    console.error('Database connection error:', err.stack);
  } else {
    console.log('Connected to Supabase PostgreSQL database');
  }
});
